# docker-compose.yml
services:
  banco-mysql-ranking: # Nome do serviço alterado para refletir MySQL
    image: mysql:8 # Imagem do MySQL
    restart: unless-stopped
    container_name: banco-mysql-ranking
    environment:
      MYSQL_ROOT_PASSWORD: fslab # Senha do usuário root do MySQL
      MYSQL_DATABASE: db_ranking # Nome do banco de dados
      MYSQL_USER: user_ranking # Nome de usuário para o banco de dados (pode ser o mesmo que o root se preferir, mas é boa prática ter um usuário específico)
      MYSQL_PASSWORD: fslab # Senha para o usuário user_ranking
    ports:
      - "3307:3306" # Porta externa 3307 mapeada para a porta padrão do MySQL 3306
    volumes:
      - volume-mysql:/var/lib/mysql # Volume para persistência dos dados do MySQL
    networks:
      - app-network

  ranking-back:
    build:
      context: ./
    container_name: ranking-back
    ports:
      - "3020:3020"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      DATAURL: "mysql://user_ranking:fslab@banco-mysql-ranking:3306/db_ranking"

volumes:
  volume-mysql: # Volume renomeado para refletir MySQL

networks:
  app-network:
    driver: bridge
